#!/bin/sh
set -e
NAME=$1
mkdir $NAME
mkdir $NAME/img
mkdir $NAME/data
cp -r .hide/tex $NAME/tex
mkdir $NAME/jupyter
cp .hide/Makefile $NAME/Makefile
cp .hide/data.csv $NAME/data/data.csv
ln -s /home/leonid/github.com/LeonidPilyugin/python-lab/src/lab $NAME/jupyter/lab
ln -s /home/leonid/Documents/Phystech/общесос/лабы/lab/.hide/.vim $NAME/.vim
cp .hide/default.ipynb $NAME/jupyter/$NAME.ipynb
